### ISSUE TITLE
Can't progress passed 'applied-for-or-received-any-other-compensation' page

### ISSUE THREAD

**Issue by armoj** [CriminalInjuriesCompensationAuthority/cica-web#19]
On the "applicant-have-you-applied-for-or-received-any-other-compensation" page.
If I fill out the page with the following...

![image](https://user-images.githubusercontent.com/29428089/60272993-10522200-98ed-11e9-98eb-35a927402bc9.png)

I am unable to progress to the next page. It appears to be causing an error, but unable to show the error. 

Pasting the relative JSON schema for this page in to http://www.jsonschemavalidator.net produces this output:

![image](https://user-images.githubusercontent.com/29428089/60273425-07ae1b80-98ee-11e9-9f73-6e2c9d987ed5.png)

The current rendering logic does not know how to handle this error, however....

If I alter the JSON schema to include "q-applicant-applied-for-other-compensation-briefly-explain-why-not" in the enum by default, and not conditionally, then...

![image](https://user-images.githubusercontent.com/29428089/60273601-65426800-98ee-11e9-88bf-8365db5f7c61.png)

I validates, and using this altered JSON schema in my local app allows me to progress to the next page as expected.

**Comment by BarryPiccinni** [comment]
This should be fixed as of version 0.0.1 of the questionnaire.
